import React from 'react'

export const metadata = {
  title: "Products Store",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <h1>Welcome to the Products Store</h1>
    </div>
  )
}

export default page