import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "./components/Header";
import Providers from "./providers";
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
 
  const myCookies=await cookies();
 const token = myCookies.get("token");

  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body
        style={{ height: "100vh", display: "flex", flexDirection: "column" }}
      >
        <Providers> 
        <Header isLogged={!!token}></Header>

        {children}
        <footer
          style={{
            backgroundColor: "#f6f6f6",
            position: "absolute",
            bottom: 0,
            width: "100%",
            padding: "1rem",
          }}
        >
          <p>&copy; 2026 My App. All rights reserved.</p>
        </footer>
        </Providers>
      </body>
    </html>
  );
}
